name: CI

on:
  push:
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - name: Clonacion de codigo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'temurin'
      
      - name: Compilacion
        run: |
          mvn package
          
      - name: Ejecucion Test Unitarios
        run: |
          mvn clean verify
    
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Analisis SonarCloud
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
          -Dsonar.token=${{ secrets.MS_KEY }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=jamoar \
          -Dsonar.projectKey=Jamoar_microservicio-java-devops
          
      - name: SonarQube Quality Gate Check
        env:
          SONAR_TOKEN: ${{ secrets.MS_KEY }}
        uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
        with:
          scanMetadataReportFile: target/sonar/report-task.txt
                    

                
