name: CI

on:
  push:
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - name: Clonacion de codigo
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'temurin'
      
      - name: Compilacion
        run: |
          mvn package
          
      - name: Ejecucion Test Unitarios
        run: |
          mvn clean verify
    
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Analisis SonarCloud
        run: |
          mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
          -Dsonar.token=${{ secrets.MS_KEY }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=jamoar \
          -Dsonar.projectKey=Jamoar_microservicio-java-devops
          
     # - name: SonarQube Quality Gate Check
     #   uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
      #  with:
     #     scanMetadataReportFile: target/sonar/report-task.txt
    #    env:
    #      SONAR_TOKEN: ${{ secrets.MS_KEY }}
    #      SONAR_HOST_URL: https://sonarcloud.io       





      - name: Login Docker
        uses: docker/login-action@v3.1.0
        with:
          username: josemorales20
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Setup de Docker
        uses: docker/setup-buildx-action@v3
        
      - name: Build and push microservicio
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USER }}/microservicio-java-devops:latest
